RuslanSlepuhin/server_bot

- sites/sites_additional_utils/ask_gemini.py
- sites/write_each_vacancy_to_db.py
> Add Gemini checker before writing to the database

- sites/sites_additional_utils/ask_gemini.py
Обработана ошибка в случае если один из серверов не ответит
> Handle an error in ask_gemini.py

- sites/write_each_vacancy_to_db.py
Проверка нейросетью Gemini перемещена после проверки присутствия вакансии в базе данных по тексту вакансии (плюс заголовок) и по URL вакансии.
> Replace the Gemini checker after the database existance checker

- sites/write_each_vacancy_to_db.py
Перемещены еще две проверки нейросетью Gemini под условие о том, присутствует ли вакансия в базе данных или нет. Если вакансия в базе данных уже присутствует - никакие проверки Gemini не будут выполняться.
> Fix Gemini checks

- sites/scraping_hh.py
- sites/write_each_vacancy_to_db.py
There was no backslashes or whitespaces. 
The entire text was written together. 
It was unreadable.
> Fix a vacancy body text formatting for site scraper

- sites/write_each_vacancy_to_db.py
Extend the regular expression for checking Gemini answer.
> Add one more if statement  for Gemini checks

- sites/write_each_vacancy_to_db.py
This is to see if there are more vacancies for designers.
> Remove 'Is IT?' gemini check temporarily

- sites/scraping_hh.py
Иногда вебдрайвер не может сформировать список линков на странице поисковой выдачи вакансий, хотя эти линки на странице есть. Это попытка устранить это.
Но в HTML коде страницы есть то, что нужно найти.
> Fix the bug when the list of found vacancies is empty

- sites/scraping_hh.py
На странице hh.ru есть чекбокс для отсева вакансий по принадлежности к ИТ сектору. Это попытка им воспользоваться.
> Filter the vacancies once they have been found

- utils/additional_variables/additional_variables.py
Цель посмотреть объем найденных вакансий в случае если поиск будет начинаться со слова 'designer'.
Вакансий дизайнеров больше , чем вакансий по слову 'junior', но в БД заносится несоизмеримо меньше.
Цель найти почему.
> Change search word place in the list

- sites/parsing_sites_runner.py
- sites/scraping_wellfound.py
Парсер для https://wellfound.com
> add parsing https://wellfound.com

- sites/parsing_sites_runner.py
Отключение всех парсеров кроме hh.ru чтобы узнать в чем задержка времени парсинга
> Switch parsers off

- sites/parsing_sites_runner.py
> Revert back all the parsers

- sites/scraping_hh.py
Небольшое ускорение скрейпера hh.ru:
1. Изменены параметры query string для поискового запроса на получение списка вакансий по ключевому слову.
2. Добавлены параметры для query string второго и последующих запросов для выполнения аостраничной навигации
> Speed up hh scraper

- sites/scraping_epam_anywhere.py
Исправлена ошибка наследования от класса HHGetinformation.
Из этого класса передавался по наследству url , строка запроса которого не соответствовала сайту EPAM. 
Исключен поиск по ключевым словам. 
Вместо него добавлена сплошная  постраничная навигация по всем вакансиям.
Добавлена сортировка поисковой выдачи по убыванию даты публикации.  
Переопределен метод get_info(). Теперь в нем нет поиска по ключевым словам, url соответствует сайту, количество поисковых страниц изменено.
> Fix inheritance error in epam scraper

- sites/write_each_vacancy_to_db.py
Удалены лишние запросы к Gemini (не информативны, замедляют процесс)
Оставлен единственный запрос на предмет относится ли данная вакансия к ИТ (действительно необходимый, работающий, проверенный фильтр)
> Reduce and fix gemini checks

- db_operations/scraping_db.py
- invite_bot_ver2.py
Добавлена возможность видеть общее количество собранных вакансий за текущие сутки по каждому чату (сайту) - источнику. По команде из Телеграм бота придет ответ:
> Add a command to the bot to get the vacancies numbers for certain chats.

- db_operations/scraping_db.py
Добавлен итоговый подсчет количества вакансий в Телеграм бот
> Add total vacancies number to bot message.

- sites/scraping_hh_it.py
> Fix attribute error in HHITGetinformation class.

- invite_bot_ver2.py
> start without client

- _apps/coffee_customer_bot_apps/coffee_horeca_bot/coffee_horeca_bot_NEW.py
- _apps/coffee_customer_bot_apps/coffee_horeca_bot/horeca_add_methods_NEW.py
- _apps/coffee_customer_bot_apps/coffee_horeca_bot/webhook.py
- _apps/coffee_customer_bot_apps/variables/variables.py
some additions for running coffee_bot
> coffee_bot

- filters/filter_jan_2023/filter_jan_2023.py
- sites/write_each_vacancy_to_db.py
Возвращен встроенный фильтр профессий как альтернатива забаненной Gemini.
> Revert back mex filter

- filters/filter_jan_2023/filter_jan_2023.py
- sites/sites_additional_utils/ask_ai.py
- sites/sites_additional_utils/question.py
1. Подключена возможность использовать другую нейросеть по причине бана Gemini.
2. Опять отключен встроенный фильтр 'mex' , который недавно был включен как альтернатива Gemini.
3. Логика формирования вопроса к нейросети вынесена в отдельный файл.
> Add new ai network 

- sites/write_each_vacancy_to_db.py
Добавлена новая нейросеть для проверки относится ли вакансия к IT
> Add a check weather the vacancy relates to IT using new neural network

- sites/write_each_vacancy_to_db.py
Закомментировано пока (проверка новой нейронкой) до лучших времен
> Comment the new neural network checks as reserved.

- sites/sites_additional_utils/ask_ai.py
Now the function can accept strait question for it's strait usage.
Добавлена возможность пользоваться функцией напрямую передав в нее текст вопроса.
> Refactor 'ask_ai' function

- parsers/hh_threadings.py
- sites/write_each_vacancy_to_db.py
Заменена сеть Gemini на сеть Llama.
Так же сокращен код для работы с потоками при помощи функции exec()
> Replace 'Gemini' neural network with 'Llama' neural network.

- sites/sites_additional_utils/ask_ai.py
- sites/write_each_vacancy_to_db.py
По причине того, что нейросеть не успевает ответить изменен тип ее вызывающей функции на асинхронную.
> Change the type of ai response function to async.

- parsers/run_parsers.py
- sites/sites_additional_utils/ask_ai.py
- sites/write_each_vacancy_to_db.py
Цель проверить многопоточность при работе парсера hh.ru
Закомментирован код для обращения к нейросети.
Возвращено код многопоточной работы парсера hh.ru.
> Revert back parsers' threadings and ecxlude all the neural tetworks checks

- _apps/endpoints/endpoints.py
- parsers/check_vacancies_without_AI.py
Два эндпоинта, чтобы доставать вакансии для обучения кастомной AI из базы проекта
> endpoints get_with_ai

- _apps/shorts_poster/shorts_poster.py
Попытка удалить эти 'None' из объявления
> Remove 'None' from publications

- _apps/shorts_poster/shorts_poster.py
Убрал название компании и компанию из текста сообщения
> убрал название компании и компанию из текста сообщения

- _apps/itcoty_web/api/urls.py
- _apps/itcoty_web/api/views/vacancies.py
- _apps/itcoty_web/itcoty_web/settings.py
has been fixed the bug to get vacancies with limit and offset query_params
> old vacancies

- _apps/itcoty_web/README.md
The ```README.md``` file has been added to the Django project .
Close #302
> Add README.md to run the app in Docker.

- _apps/itcoty_web/README.md
- _apps/itcoty_web/docker-compose.yml
- Extend the description.
- Close #302
> Add README.md to run the app in Docker. 

- _apps/itcoty_web/README.md
> Refresh README.md and fix syntax errors in it.

- _apps/itcoty_web/itcoty_web/envs.py
- _apps/itcoty_web/itcoty_web/settings.py
The project sensitive variables such as:
- smtp host;
- smtp port;
- smtp user email;
- application password;
- etc.
-have been hidden into ```.env``` file.
For now the email confirmation still doesn't work but the email is sent.
Close #308
> Hide the project sensitive variables related to email confirmation.

- _apps/itcoty_web/api/urls.py
- Ada an url to process the email confirmation.
- Close #310
> Fix the email confirmation process.

- _apps/itcoty_web/example.env
- Update hhe email confirmation cedential.
- Close #310
> Set an email confirmation example credentials.

- _apps/itcoty_web/.dockerignore
- _apps/itcoty_web/docker-compose.yml
- Add a sample dockerignore file.
> Ignore some files for Docker.

- _apps/itcoty_web/README.md
- _apps/itcoty_web/docker-compose.yml
- _apps/itcoty_web/docker-entrypoint.sh
- Fix CRLF error for docker-entrypoint.sh.
- Update README according to that.
- Fix an error when helthchecking the DB.
> Fix errors in docker entrypoints.

- _apps/itcoty_web/itcoty_web/settings.py
Add a series of CORS headers to avoid an errror .
Close #320
> Extend default CORS haeers.

- _apps/itcoty_web/README.md
- _apps/itcoty_web/example.env
- Update the instruction on how to run the Django app on a localhost.
- Add the example environment variables to this issue.
- Close #328
> Add the ability to run the Django app on localhost

- _apps/itcoty_web/docker-compose.yml
- _apps/itcoty_web/nginx.conf
Change ports' numbers to avoid errors when launching on the server. 
There is a series of apps running on the server that use the same ports.
> Change the Docker containers external ports' numbers.

- _apps/itcoty_web/nginx.conf
There are a few apps runnin on the dev server. The issue is to define the Docker ones this way.
> Change the Docker containers location API point.

- _apps/itcoty_web/nginx.conf
The issue is to redirect localhost requests to the dev server. The commom nginx configuration must work both on the dev server and localhost.
> Add localhost and server names to the nginx server configuration.

- _apps/itcoty_web/Taskfile.yml
The command to update 'node' service was incorrect. There was no updating there.
> Fix 'node' service updating command.

- _apps/itcoty_web/Taskfile.yml
Fix the docker image updating command according to the placement where the app will be running.
> Add a variable to detect placement when pulling a docker image.

- _apps/itcoty_web/Taskfile.yml
Fix an error in tag name in one of the tasks.
> Fix an error in tag name in a task.

- _apps/itcoty_web/api/adapters.py
- _apps/itcoty_web/api/urls.py
- _apps/itcoty_web/api/views/__init__.py
- _apps/itcoty_web/api/views/registration.py
- _apps/itcoty_web/itcoty_web/drfout.py
- _apps/itcoty_web/itcoty_web/settings.py
When a user receives a confirmation letter on email they might get registered just by 
following the link in the letter.
> Confirm email using GET request when registered.

- .gitignore
- _apps/itcoty_web/itcoty_web/drfout.py
An error occurs because this file is missing before running the app. Fix the error this way.
#327
> Unignore dev settings file.

- _apps/itcoty_web/docker-compose.yml
- _apps/itcoty_web/docker-entrypoint.sh
Once the app starts for the first time there is no dev settings file created yet. Fix that error.
#327
> Fix an error when there is no dev settings file created once the app starts for the first time.

- _apps/itcoty_web/README.md
- _apps/itcoty_web/Taskfile.yml
Add a task command to launch just the backend part of the project with all the dependent services.
> Add a comand to run the backend part only.

- _apps/itcoty_web/itcoty_web/dirs.py
Create these folders if not exist.
> Create '.local' and 'static' folders if launching firs time
